CarolineBergen/Models/ContactViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CarolineBergen.Models
{
    public class ContactViewModel
    {
        [Required]
        [Display(Name = "Name")]
        public string Name
        { get; set; }
        [Required]
        [Display(Name = "Email")]
        [EmailAddress(ErrorMessage = "Invalid Email.")]
        public string Email
        { get; set; }
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password
        { get; set; }
        [Required(ErrorMessage = "Please include a description.")]
        [Display(Name="Tell us about your project")]
        public string BodyMessage
        { get; set; }

    }
}

CarolineBergen/Models/ErrorViewModel.cs
using System;

namespace CarolineBergen.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CarolineBergen/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CarolineBergen.Models;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc.Localization;
using System.Net.Mail;
using System.Net;

namespace CarolineBergen.Controllers
{
    public class HomeController : Controller
    {
        private const string personalToMail = "thisisnotarealemail@gmail.com";//"splitkegan@gmail.com";//"sujitc19@gmail.com";//caroline.bergen@outlook.com

        public IActionResult Index()
        {
            //this is a test...
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Contact()
        {
            if (TempData["EmailSentStatus"] != null)
            {
                ViewBag.EmailSentStatus = TempData["EmailSentStatus"];
            }
            else
            {
                ViewBag.EmailSentStatus = false;
            }
            ViewData["Message"] = "Contact Information";
            return View(new ContactViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Contact([FromForm] ContactViewModel model)
        {
            ViewData["Message"] = "Contact Information";
            if (!ModelState.IsValid)
            {
                ViewBag.EmailSentStatus = false;
                return View();
            }
            else
            {
                MailAddress From = new MailAddress(model.Email);
                MailAddress To = new MailAddress(personalToMail);
                MailMessage message = new MailMessage(From, To);
                message.Subject = $"{model.Name}'s Request via site mailer";
                message.Body = model.BodyMessage;

                try
                {
                    var smtp = new System.Net.Mail.SmtpClient();
                    {
                        smtp.Host = "smtp.gmail.com";
                        smtp.Port = 587;
                        smtp.Credentials = new NetworkCredential(model.Email, model.Password);
                        smtp.EnableSsl = true;
                        smtp.DeliveryMethod = System.Net.Mail.SmtpDeliveryMethod.Network;
                        smtp.Timeout = 20000;
                    }
                    
                    smtp.Send(message);
                }
                catch (Exception ex)
                {
                    ViewBag.ErrorMessage = ex.Message + "\n" + ex.StackTrace;
                    ViewBag.EmailSentStatus = false;
                    return View();
                }

                TempData["EmailSentStatus"] = true;
                return RedirectToAction("Contact");
            }
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CarolineBergen/Controllers/PortfolioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace CarolineBergen.Controllers
{
    public class PortfolioController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult illustrations()
        {
            return View();
        }

        public IActionResult graphicDesign()
        {
            return View();
        }

        public IActionResult traditional()
        {
            return View();
        }

        public IActionResult comics()
        {
            return View();
        }

        public IActionResult gridderDemo()
        {
            return View();
        }
    }
}

CarolineBergen/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<!--<br />
<div class="row">
    <div class="col-lg-6">
        <img src="~/images/bookforweb.jpg" style="width:100%" />
    </div>
    <div class="col-lg-6">
        <h3 style="font-family:Allan; color:coral">Hello!</h3>
        <p>
            My name is Caroline.
            In 2016 I graduated with honors in Graphic Design in Warsaw, Poland. I moved to
            USA and was working for almost a year as a Graphic Artist in the company that was making promotional products. After that I started working as a Graphic Designer in a print shop where I work today. I am a hardworking, creative designer who is not afraid of
            new challenges and is willing to go extra mile to make sure that the clients gets exactly what they want.
        </p>
    </div>
</div>-->
<div class="container">
<div class="portfolioSection">
    <div class="row">
        <div class="col-md-6">
    <div class="aboutPhoto">
        <img src="~/images/About Me-01-01.png" />
    </div>
            </div>
        <div class="col-md-6">
    <div class="aboutDescription">
        <h2 class="aboutTitle">About</h2>
        <p>
            I’m an artist - graphic designer, painter, and illustrator. Born in Poland, I now live in the USA with my American husband.
        </p><br /><p>
            My current work includes a position at a print shop as a graphic designer and as a freelancer for children’s illustrations, paintings, digital art, and graphic design projects. I also make comic strips about long distance and multicultural relationships that you are welcome to check out in my <a asp-area="" asp-controller="Portfolio" asp-action="Index">PORTFOLIO</a>.
        </p><br /><p>
            For commission inquiries, freelance work, or other questions, please contact me by visiting the <a asp-area="" asp-controller="Home" asp-action="Contact">CONTACT</a> link.
        </p><br /><p>
            Please make sure to check out my pricing and get familiar with my requirements first by clicking the <a asp-area="" asp-controller="Home" asp-action="Contact">CONTACT</a> button.
        </p>
        <div class="signature">
            <img src="~/images/sig.png" alt="signature Caroline Bergen" class="signatureLine" />
        </div>
        <div class="socialBar">
            <p>Find me on social media!</p>
            <img src="~/images/socialicons.png" alt="social media icons" class="socialIcons" />
        </div>
    </div>
            </div>
</div>
    </div>
</div>

CarolineBergen/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div class="wrapper">

</div>

CarolineBergen/Views/Portfolio/GraphicDesign.cshtml
@{
    ViewData["Title"] = "GraphicDesign";
}
<div class="portfolioSection">
    <h2 class="portfolioSectionTitle">Graphic Design</h2>
    <p><center>A collection of digital work created both for personal use and on commission.</center></p><br/>
    <!-- Gridder navigation -->
    <ul class="gridder">

        <!-- You can load specify which content is loaded by specifying the #ID of the div where the content is  -->
        <li class="gridder-list" data-griddercontent="#content1">
            <img src="~/images/graphicDesign/Cup--dogs1.jpg" width="300px" />
        </li>
        <li class="gridder-list" data-griddercontent="#content2">
            <img src="~/images/graphicDesign/H_N_1.jpg" width="300px" />
        </li>
        <li class="gridder-list" data-griddercontent="#content3">
            <img src="~/images/graphicDesign/Merry-Christmas-Cards_1.jpg" width="300px" />
        </li>
        <li class="gridder-list" data-griddercontent="#content4">
            <img src="~/images/graphicDesign/Pozytyw_1.jpg" width="300px" />
        </li>
        <li class="gridder-list" data-griddercontent="#content5">
            <img src="~/images/graphicDesign/Polas-Wedding-invitation_1.jpg" width="300px" />
        </li>
        <li class="gridder-list" data-griddercontent="#content6">
            <img src="~/images/graphicDesign/Queen-of-Spiders-Design.jpg" width="300px" />
        </li>
        <li class="gridder-list" data-griddercontent="#content7">
            <img src="~/images/graphicDesign/Sherlock-Holmes-Design.jpg" width="300px" />
        </li>
        <li class="gridder-list" data-griddercontent="#content8">
            <img src="~/images/graphicDesign/Wedding-Invitation-Travel_1.jpg" width="300px" />
        </li>
        <li class="gridder-list" data-griddercontent="#content9">
            <img src="~/images/graphicDesign/I-do-not-have-a-pet-elephant-cover_3.jpg" width="300px" />
        </li>
        <li class="gridder-list" data-griddercontent="#content10">
            <img src="~/images/graphicDesign/ilink_1.jpg" width="300px" />
        </li>
    </ul>

    <!-- Gridder content -->
    <div id="content1" class="gridder-content">
        <img src="~/images/graphicDesign/Cup--dogs1.jpg" />
        <div class="description">
            <h2>Design for a gift mug (Commissioned)</h2><h3>
                Personalized illustration based on a photograph of the gift
                recipient with added elements as requested - printed on mug.
            </h3>
        </div>
    </div>
    <div id="content2" class="gridder-content">
        <img src="~/images/graphicDesign/H_N_1.jpg" />
        <div class="description">
            <h2>
                Promotional Material (Commissioned)
                Logo, Profile Pictures, and Website Banner
            </h2><h3>
                Promotional material requested to have the letter 'H' and 'N' in the the
                style of a classic superhero logo. Profile pictures resembling the requesters.
                And a banner incorporating all of the previous elements.
            </h3>
        </div>
    </div>
    <div id="content3" class="gridder-content">
        <img src="~/images/graphicDesign/Merry-Christmas-Cards_1.jpg" />
        <div class="description">
            <h2>Christmas Cards (Personal)</h2><h3>
                Two sided Christmas Card designs with an emphasis on
                typography. Designed with space to write personalised greetings.
                (Meant to be sent with envelope - no postal marks in design)
            </h3>
        </div>
    </div>
    <div id="content4" class="gridder-content">
        <img src="~/images/graphicDesign/Pozytyw_1.jpg" />
        <div class="description">
            <h2>
                POZYTYW
                Stationary Set with Custom Logo (Commissioned)
            </h2><h3>
                Letterhead, Envelope, Business Cards (multiple variations), and Custom Logo
            </h3>
        </div>
    </div>
    <div id="content5" class="gridder-content">
        <img src="~/images/graphicDesign/Polas-Wedding-invitation_1.jpg" />
        <div class="description">
            <h2>
                Wedding Invitations (Commissioned)
            </h2><h3>
                Wedding invitations personalized as requested by the couple to be.
                Designed in a way that the information is segmented into three parts
                (invitation, ceremony, and reception).
            </h3>
        </div>
    </div>
    <div id="content6" class="gridder-content">
        <img src="~/images/graphicDesign/Queen-of-Spiders-Design.jpg" />
        <div class="description">
            <h2>
                Book Cover 'Queen of Spiders' (Personal)
            </h2><h3>
                A book cover design for a children's story.
            </h3>
        </div>
    </div>
    <div id="content7" class="gridder-content">
        <img src="~/images/graphicDesign/Sherlock-Holmes-Design.jpg" />
        <div class="description">
            <h2>
                Book Cover 'Sherlock Holmes' (Personal)
            </h2><h3>
                A book cover design for the famous sleuth.
            </h3>
        </div>
    </div>
    <div id="content8" class="gridder-content">
        <img src="~/images/graphicDesign/Wedding-Invitation-Travel_1.jpg" />
        <div class="description">
            <h2>
                Wedding Invitations (Personal)
            </h2><h3>
                Travel themed wedding invitations with a vintage aesthetic. Created for
                personal use for my own wedding. Invitations were meant to reflect our
                long distant relationship, showing the connection between Poland and the
                United States. Invitations went along with the overall 'travel' theme.
            </h3>
        </div>
    </div>
    <div id="content9" class="gridder-content">
        <img src="~/images/graphicDesign/I-do-not-have-a-pet-elephant-cover_3.jpg" />
        <div class="description">
            <h2>
                Book Cover 'I Do Not Have A Pet Elephant'
            </h2><h3>
    A book cover design for a children's story about a girl with a pet elephant,
    and all the creative lengths she goes to hide it.
</h3>
        </div>
    </div>
    <div id="content10" class="gridder-content">
        <img src="~/images/graphicDesign/ilink_1.jpg" />
        <div class="description">
            <h2>
                ILINK
                Stationary Set with Custom Logo (Commissioned)
            </h2><h3>
    Letterhead, Envelope, Business Cards, and Custom Logo
</h3>
        </div>
    </div>

    <div><a asp-area="" asp-controller="Portfolio" asp-action="Index" style="color:#166dbe">Back</a></div>

    <script>
        $(document).ready(function () {
            // Call Gridder
            $(".gridder").gridderExpander({
                scrollOffset: 60,
                scrollTo: "panel", // "panel" or "listitem"
                animationSpeed: 400,
                animationEasing: "easeInOutExpo",
                onStart: function () {
                    console.log("Gridder Inititialized");
                },
                onExpanded: function (object) {
                    console.log("Gridder Expanded");
                },
                onChanged: function (object) {
                    console.log("Gridder Changed");
                },
                onClosed: function () {
                    console.log("Gridder Closed");
                }
            });
        });</script>
</div>

CarolineBergen/Views/Portfolio/Illustrations.cshtml
@{
    ViewData["Title"] = "illustrations";
}

<div class="portfolioSection">
    <h2 class="portfolioSectionTitle">Illustrations</h2>
    <p><center>A collection of illustrations using traditional media, Photoshop, and Illustrator.</center></p>
    <!-- Gridder navigation -->
    <ul class="gridder">

        <!-- You can load specify which content is loaded by specifying the #ID of the div where the content is  -->
        <li class="gridder-list" data-griddercontent="#content1">
            <img src="~/images/illustration/Beach-Girl_2.jpg" width="300px" />
        </li>
        <li class="gridder-list" data-griddercontent="#content2">
            <img src="~/images/illustration/Bike-at-the-Sea_2.jpg" width="300px" />
        </li>
        <li class="gridder-list" data-griddercontent="#content3">
            <img src="~/images/illustration/Book_3.jpg" width="300px" />
        </li>
        <li class="gridder-list" data-griddercontent="#content4">
            <img src="~/images/illustration/Bunny_s-Dream_4.jpg" width="300px" />
        </li>
        <li class="gridder-list" data-griddercontent="#content5">
            <img src="~/images/illustration/Bunny-in-a-Bow-Tie_2.jpg" width="300px" />
        </li>
        <li class="gridder-list" data-griddercontent="#content6">
            <img src="~/images/illustration/Happy-in-the-Rain_1.jpg" width="300px" />
        </li>
        <li class="gridder-list" data-griddercontent="#content7">
            <img src="~/images/illustration/Kitten_3.jpg" width="300px" />
        </li>
        <li class="gridder-list" data-griddercontent="#content8">
            <img src="~/images/illustration/Concept-Art-Girl-and-Aunt_5.jpg" width="300px" />
        </li>
        <li class="gridder-list" data-griddercontent="#content9">
            <img src="~/images/illustration/Concept-Art-for-Thesis_12.jpg" width="300px" />
        </li>
        <li class="gridder-list" data-griddercontent="#content10">
            <img src="~/images/illustration/Grumpy-Boy_2.jpg" width="300px" />
        </li>
        <li class="gridder-list" data-griddercontent="#content11">
            <img src="~/images/illustration/Kasia_s-Kookies_2.jpg" width="300px" />
        </li>
        <li class="gridder-list" data-griddercontent="#content12">
            <img src="~/images/illustration/Mary_2.jpg" width="300px" />
        </li>
        <li class="gridder-list" data-griddercontent="#content13">
            <img src="~/images/illustration/Penguin_2.jpg" width="300px" />
        </li>
        <li class="gridder-list" data-griddercontent="#content14">
            <img src="~/images/illustration/Clock_6.jpg" width="300px" />
        </li>
        <li class="gridder-list" data-griddercontent="#content15">
            <img src="~/images/illustration/Clock-Fix_1.jpg" width="300px" />
        </li>
        <li class="gridder-list" data-griddercontent="#content16">
            <img src="~/images/illustration/Fire_1.jpg" width="300px" />
        </li>
        <li class="gridder-list" data-griddercontent="#content17">
            <img src="~/images/illustration/Puzzle_1.jpg" width="300px" />
        </li>
        <li class="gridder-list" data-griddercontent="#content18">
            <img src="~/images/illustration/Sculpture_2.jpg" width="300px" />
        </li>
        <li class="gridder-list" data-griddercontent="#content19">
            <img src="~/images/illustration/Picnic_2.jpg" width="300px" />
        </li>
        <li class="gridder-list" data-griddercontent="#content20">
            <img src="~/images/illustration/Portraits_4.jpg" width="300px" />
        </li>
        <li class="gridder-list" data-griddercontent="#content21">
            <img src="~/images/illustration/Family_1.jpg" width="300px" />
        </li>
        <li class="gridder-list" data-griddercontent="#content22">
            <img src="~/images/illustration/Vintage-Portrait_1.jpg" width="300px" />
        </li>
    </ul>

    <!-- Gridder content -->
    <div id="content1" class="gridder-content">
        <img src="~/images/illustration/Beach-Girl_2.jpg" />
        <div class="description"><h2>BEACH LADY</h2><h3>Made in Adobe Illustrator.</h3></div>
    </div>
    <div id="content2" class="gridder-content">
        <img src="~/images/illustration/Bike-at-the-Sea_2.jpg" />
        <div class="description"><h2>BIKE AT THE SEA</h2><h3>Made in Adobe Illustrator.</h3></div>
    </div>
    <div id="content3" class="gridder-content">
        <img src="~/images/illustration/Book_3.jpg" />
        <div class="description"><h2>READING</h2><h3>Made in Adobe Illustrator.</h3></div>
    </div>
    <div id="content4" class="gridder-content">
        <img src="~/images/illustration/Bunny_s-Dream_4.jpg" />
        <div class="description"><h2>BUNNY'S DREAM</h2><h3>Made in Adobe Illustrator.</h3></div>
    </div>
    <div id="content5" class="gridder-content">
        <img src="~/images/illustration/Bunny-in-a-Bow-Tie_2.jpg" />
        <div class="description"><h2>BUNNY IN A BOW TIE</h2><h3>Hand drawn Illustration. Ink and watercolor on paper.</h3></div>
    </div>
    <div id="content6" class="gridder-content">
        <img src="~/images/illustration/Happy-in-the-Rain_1.jpg" />
        <div class="description"><h2>HAPPY IN THE RAIN</h2><h3>Made in Adobe Photoshop.</h3></div>
    </div>
    <div id="content7" class="gridder-content">
        <img src="~/images/illustration/Kitten_3.jpg" />
        <div class="description"><h2>KITTEN</h2><h3>Made in Adobe Photoshop.</h3></div>
    </div>
    <div id="content8" class="gridder-content">
        <img src="~/images/illustration/Concept-Art-Girl-and-Aunt_5.jpg" />
        <div class="description"><h2>CONCEPT ART FOR GIRL AND AUNT</h2><h3>Concept Art of the Little Mean Girl and her aunt for a Victorian styled children's story.</h3></div>
    </div>
    <div id="content9" class="gridder-content">
        <img src="~/images/illustration/Concept-Art-for-Thesis_12.jpg" />
        <div class="description">
            <h2>CONCEPT ART FOR MY THESIS</h2><h3>
                Concept art for my university thesis, a short animation video. The short was designed to be
                creepy in a Victorian style. The main character is known simply as 'The Woman', she becomes
                undone during the short - as reflected in her hairstyle.
                The backgrounds and objects were created in Adobe Photoshop.
                The characters were created in Adobe Flash.
            </h3>
        </div>
    </div>
    <div id="content10" class="gridder-content">
        <img src="~/images/illustration/Grumpy-Boy_1.jpg" />
        <div class="description"><h2>GRUMPY BOY</h2><h3>Made in Adobe Illustrator.</h3></div>
    </div>
    <div id="content11" class="gridder-content">
        <img src="~/images/illustration/Kasia_s-Kookies_1.jpg" />
        <div class="description"><h2>KASIA'S KOOKIES</h2><h3>Made in Adobe Photoshop.</h3></div>
    </div>
    <div id="content12" class="gridder-content">
        <img src="~/images/illustration/Mary_1.jpg" />
        <div class="description"><h2>MARY</h2><h3>Made in Adobe Photoshop. A design for a character that will be a part of a series of illustrations about an explorer. </h3></div>
    </div>
    <div id="content13" class="gridder-content">
        <img src="~/images/illustration/Penguin_1.jpg" />
        <div class="description"><h2>PENGUIN</h2><h3>Made in Adobe Photoshop.</h3></div>
    </div>
    <div id="content14" class="gridder-content">
        <img src="~/images/illustration/Clock_6.jpg" />
        <div class="description"><h2>CLOCK</h2><h3>Photomanipulation made in Adobe Photoshop. </h3></div>
    </div>
    <div id="content15" class="gridder-content">
        <img src="~/images/illustration/Clock-Fix_1.jpg" />
        <div class="description"><h2>CLOCK FIX</h2><h3>Photomanipulation made in Adobe Photoshop.</h3></div>
    </div>
    <div id="content16" class="gridder-content">
        <img src="~/images/illustration/Fire_1.jpg" />
        <div class="description"><h2>FIRE</h2><h3>Photomanipulation made in Adobe Photoshop.</h3></div>
    </div>
    <div id="content17" class="gridder-content">
        <img src="~/images/illustration/Puzzle_1.jpg" />
        <div class="description"><h2>PUZZLE</h2><h3>Photomanipulation made in Adobe Photoshop.</h3></div>
    </div>
    <div id="content18" class="gridder-content">
        <img src="~/images/illustration/Sculpture_1.jpg" />
        <div class="description"><h2>SCULPTURE</h2><h3>Photomanipulation made in Adobe Photoshop.</h3></div>
    </div>
    <div id="content19" class="gridder-content">
        <img src="~/images/illustration/Picnic_1.jpg" />
        <div class="description"><h2>PICNIC</h2><h3>Made in Adobe Photoshop.</h3></div>
    </div>
    <div id="content20" class="gridder-content">
        <img src="~/images/illustration/Portraits_4.jpg" />
        <div class="description"><h2>PORTRAITS</h2><h3>Made in Adobe Photoshop.</h3></div>
    </div>
    <div id="content21" class="gridder-content">
        <img src="~/images/illustration/Family_1.jpg" />
        <div class="description"><h2>THE FAMILY</h2><h3>Concept design of a family. Made in Adobe Photoshop.</h3></div>
    </div>
    <div id="content22" class="gridder-content">
        <img src="~/images/illustration/Vintage-Portrait_1.jpg" />
        <div class="description"><h2>VINTAGE PORTRAIT OF AN ARTIST</h2><h3>
    Digital Illustration<br/>
    Made in Adobe Photoshop, using hand drawn elements.
</h3></div>
    </div>

    <div>
        <a asp-area="" asp-controller="Portfolio" asp-action="Index" style="color:#166dbe">Back</a>
    </div>

    <script>
        $(document).ready(function () {
            // Call Gridder
            $(".gridder").gridderExpander({
                scrollOffset: 60,
                scrollTo: "panel", // "panel" or "listitem"
                animationSpeed: 400,
                animationEasing: "easeInOutExpo",
                onStart: function () {
                    console.log("Gridder initialized");
                },
                onContent: function () {
                    console.log("Gridder content loaded");
                },
                onClosed: function () {
                    console.log("Gridder closed.");
                }
            });
        });</script>
</div>

CarolineBergen/Views/Portfolio/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
<link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
<div class="container">
    <div class="portfolioSection">
        <h2 class="portfolioSectionTitle">Portfolio</h2>
        <div class="row">
            <div class="col-md-6">
                <div class="portImg">
                <a asp-area="" asp-controller="Portfolio" asp-action="graphicDesign">
                <img src="images/graphicDesign/I-do-not-have-a-pet-elephant-cover.jpg">
                    <div class="overlay">
                        <div class="bgPortText">
                            <div class="portText">Graphic Design
                            </div>
                        </div>
                    </div>
                </a>
                </div>
            </div>
            <div class="col-md-6">
                <div class="portImg">
                 <a asp-area="" asp-controller="Portfolio" asp-action="traditional">
                 <img src="images/traditional/Magnolias_3.jpg">
                    <div class="overlay">
                        <div class="bgPortText">
                            <div class="portText">Traditional Art
                            </div>
                        </div>
                    </div>
                 </a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="portImg">
                <a asp-area="" asp-controller="Portfolio" asp-action="illustrations">
                <img src="images/illustration/Bike-at-the-Sea_1.jpg">
                    <div class="overlay">
                        <div class="bgPortText">
                            <div class="portText">Illustrations
                            </div>
                        </div>
                    </div>
                </a>
                </div>
            </div>
            <div class="col-md-6">
                <div class="portImg">
                <a asp-area="" asp-controller="Portfolio" asp-action="comics">
                <img src="images/comics/comicCover.jpg">
                    <div class="overlay">
                        <div class="bgPortText">
                            <div class="portText">Comics
                            </div>
                        </div>
                    </div>
                </a>
                </div>
            </div>
        </div>
    </div>
</div>

CarolineBergen/Views/Portfolio/comics.cshtml
@{
    ViewData["Title"] = "comics";
}
<div class="portfolioSection">
    <h2 class="portfolioSectionTitle">Comics</h2>
    <p><center>A collection of comics about my relationship and the struggles of long distance.</center></p><br/>
    <!-- Gridder navigation -->
    <ul class="gridder">

        <!-- You can load specify which content is loaded by specifying the #ID of the div where the content is  -->
        <li class="gridder-list" data-griddercontent="#content1">
            <img src="~/images/comics/airport-goodbye_for-web.jpg" width="300px" />
        </li>
        <li class="gridder-list" data-griddercontent="#content2">
            <img src="~/images/comics/little-moments_fro-web.jpg" width="300px" />
        </li>
        <li class="gridder-list" data-griddercontent="#content3">
            <img src="~/images/comics/love-who-we-truly-are_for-web.jpg" width="300px" />
        </li>
        <li class="gridder-list" data-griddercontent="#content4">
            <img src="~/images/comics/skype-date_for-web.jpg" width="300px" />
        </li>
        <li class="gridder-list" data-griddercontent="#content5">
            <img src="~/images/comics/time-difference_for-web.jpg" width="300px" />
        </li>
        <li class="gridder-list" data-griddercontent="#content6">
            <img src="~/images/comics/Skype-Secrets-2_for-web.jpg" width="300px" />
        </li>
    </ul>

    <!-- Gridder content -->
    <div id="content1" class="gridder-content">
        <img src="~/images/comics/airport-goodbye_for-web.jpg" />
    </div>
    <div id="content2" class="gridder-content"> <img src="~/images/comics/little-moments_fro-web.jpg" /> </div>
    <div id="content3" class="gridder-content"> <img src="~/images/comics/love-who-we-truly-are_for-web.jpg" /> </div>
    <div id="content4" class="gridder-content"> <img src="~/images/comics/skype-date_for-web.jpg" /> </div>
    <div id="content5" class="gridder-content"> <img src="~/images/comics/time-difference_for-web.jpg" /> </div>
    <div id="content6" class="gridder-content"> <img src="~/images/comics/Skype-Secrets-2_for-web.jpg" /> </div>

    <div><a asp-area="" asp-controller="Portfolio" asp-action="Index" style="color:#166dbe">Back</a></div>

    <script>
        $(document).ready(function () {

            // Call Gridder
            $(".gridder").gridderExpander({
                scroll: true,
                scrollOffset: 60,
                scrollTo: "panel", // panel or listitem
                animationSpeed: 400,
                animationEasing: "easeInOutExpo",
                showNav: true,
                onStart: function () {
                    console.log("Gridder Inititialized");
                },
                onExpanded: function (object) {
                    console.log("Gridder Expanded");
                },
                onChanged: function (object) {
                    console.log("Gridder Changed");
                },
                onClosed: function () {
                    console.log("Gridder Closed");
                }
            });
        });
    </script>
</div>